backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  social_media:
    facebook: https://www.facebook.com/nickdandave
    instagram: https://www.instagram.com/nickdandave/
