backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "images/uploads"
public_folder: "/images/uploads"
media_library:
  name: cloudinary
  config:
    cloud_name: deepwywnm
    api_key: 997685817411955

collections:
  - label: 'Blog'
    name: 'blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Home"
        name: "home"
        file: "index.md"
        fields:
          - {label: "Display Text", name: "display_text", widget: "markdown"}
          - {label: "Display Subtext", name: "display_subtext", widget: "markdown"}
          - {label: "Hero Description", name: "hero_description", widget: "markdown"}
      - label: "About Page"
        name: "about"
        file: "about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "markdown"}
          - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'about'}
          - {label: "About Copy", name: "about_copy", widget: "markdown"}
      - label: "Ramblings"
        name: "blog"
        file: "blog.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "markdown"}
          - {label: "Intro Copy", name: "intro_copy", widget: "markdown"}
      - label: "Pantone Colors"
        name: "pantone-colors"
        file: "pantonecolors.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "markdown"}
          - {label: "Copy", name: "copy", widget: "markdown"}
  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Link, name: link, widget: string}
      - label: "Social Media"
        name: "social_media"
        file: "_data/social_media.yml"
        fields:
          - label: "Social Media Items"
            name: "items"
            widget: "list"
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Link, name: link, widget: string}
              - {label: Fa Icon, name: fa-icon, widget: string}
      - label: "Pantone Colors"
        name: "pantone_colors"
        file: "_data/pantone_colors.yml"
        fields:
          - label: "Pantone Colors"
            name: "colors"
            widget: "list"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Year, name: year, widget: string}
              - {label: "Is Double Color of the Year?", name: is_double, widget: string}
              - {label: Hex Code, name: hex_code, widget: string}
              - {label: "Is Dark Color?", name: is_dark, widget: boolean, required: false}
              - {label: Description, name: description, widget: markdown}
