backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - label: "Blog"
    name: "blog"
    folder: "_posts"
    fields:
      - {label: "Title", name: "title", widget: "markdown"}
      - {label: "Subtitle", name: "subtitle", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "about.md"
        fields:
          - {label: "Title", name: "title", widget: "markdown"}
          - {label: "Subtitle", name: "subtitle", widget: "markdown"}
          - {label: "About Copy", name: "about_copy", widget: "markdown"}
      - label: "Home"
        name: "home"
        file: "index.md"
        fields:
          - {label: "Display Text", name: "display_text", widget: "markdown"}
          - {label: "Display Subtext", name: "display_subtext", widget: "markdown"}
          - {label: "Hero Description", name: "hero_description", widget: "markdown"}
