backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About"
        name: "about"
        file: "_site/about.html"
        fields:
      - label: "Home"
        name: "home"
        file: "_site/index.html"
        fields:
    folder: "_site"
    fields:
