backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - label: "Blog"
    name: "blog"
    folder: "_posts"
    fields:
      - {label: "title", name: "Title", widget: "markdown"}
      - {label: "subtitle", name: "Subtitle", widget: "markdown"}
      - {label: "body", name: "Body", widget: "markdown"}
